#cloud-config
# Multipass cloud-init configuration for Bedrock Starter
# This only installs system dependencies. The full setup runs after mounting.

# Update system on first boot
package_update: true
package_upgrade: true

# Install git (needed for submodule initialization)
packages:
  - git
  - curl
  - software-properties-common

